### ISSUE TITLE
Error when clicking anywhere on the page

### ISSUE THREAD

**Issue by tobaco** [edenspiekermann/a11y-toggle#14]
When i click anywhere on the page i get the following error

> Uncaught TypeError: Cannot read property 'getAttribute' of null

Happens in your demo and my local dev site.

Thanks!

**Comment by KittyGiraudel** [comment]
Fixed with https://github.com/edenspiekermann/a11y-toggle/releases/tag/1.0.3. Sorry about that!

**Comment by tobaco** [comment]
Thanks!
