### ISSUE TITLE
Collapsed by default broken?

### ISSUE THREAD

**Issue by yellowled** [edenspiekermann/a11y-toggle#16]
Not sure why, but even in [the demo](http://edenspiekermann.github.io/a11y-toggle/), _both_ instances of `.collapsible-box` initially get `aria-hidden="false"`. Therefore, the “Collapsed by default” example is not actually collapsed by default.

Once the toggler button is clicked, everything works fine, but the initial state is broken. Tested in Chrome, Firefox and Safari, so probably not a browser-related issue.

(Of course, this can be fixed by assigning `aria-hidden="true"` in the markup, but surely that's not the intended use.)

**Comment by KittyGiraudel** [comment]
Hey. Should be fixed. Documentation and example were not up to date with code. Thanks for reporting. :)
