### ISSUE TITLE
Accessibility of no-JS Version

### ISSUE THREAD

**Issue by mrwweb** [edenspiekermann/a11y-toggle#19]
Looking at this, I'm wondering about a11y problems when JS is turned off (rare) or doesn't load (less rare). By requiring the `aria-hidden="true"` to be in the HTML source rather than inserted by the JS, this means that–if I'm reading this correctly—the hidden content is screen-reader-inaccessible with no JS.

The best solution I can think of right now is to introduce another data attribute (`data-a11y-toggle-default="hidden"` maybe?) on either the button or container and then settings `aria-hidden` based on that.

(And as I think about this even more, shouldn't the `<button>` be hidden when there's no JS and then made visible once JS loads?)

**Comment by KittyGiraudel** [comment]
Hey there. Thanks for the issue, I’ll investigate soon. :)

**Comment by KittyGiraudel** [comment]
Okay, so I took some time to check this. I think as of today, the best solution would be to avoid recommending people to do collapsed by default. Indeed, your hypothesis is correct and it involves accessibility issues when JavaScript is disabled (or absent). Therefore, I will update the demo page.

Maybe for the next version, it might be interesting to provide the option to make it collapsed by default without hurting no JS accessibility

**Comment by KittyGiraudel** [comment]
Closing for now. :)

**Comment by mrwweb** [comment]
I obviously can only speak for myself, but I came to this library specifically with a hidden-by-default feature in mind and I suspect that many if not a majority of others do too. Long-term, I think this idea still makes sense:

> The best solution I can think of right now is to introduce another data attribute (`data-a11y-toggle-default="hidden"` maybe?) on either the button or container [Note: Upon further thought, I think container makes most sense] and then setting `aria-hidden` based on that.

**Comment by KittyGiraudel** [comment]
I definitely think it does too. But right now, that is not what the library is doing and the documentation was therefore misleading. I shall add a feature like this in an upcoming version.
