### ISSUE TITLE
Discussion about JS performance

### ISSUE THREAD

**Issue by i-like-robots** [edenspiekermann/a11y-toggle#2]
Lovely work on this script =]

I've tested a couple of small variations on JSPerf. Small gains it seems from initial tests and I thought it may be useful to share.

http://jsperf.com/a11y-toggle/2

**Comment by KittyGiraudel** [comment]
Thank you so much for doing this. Funny how 1 `querySelectorAll` still is slower than several `getElementById`.

**Comment by i-like-robots** [comment]
Yes it's a little surprising. It needs a few more variations, my hunch is
that a single loop will be faster but I just threw that together over
breakfast!

**Comment by giuseppeg** [comment]
Another perf thing to keep in mind is that if a target is removed from the dom it will be retained in memory and can't be gc-ed because `targetsMap` references to it.

**Comment by KittyGiraudel** [comment]
Ah. Interesting. Anyway to prevent that?

**Comment by giuseppeg** [comment]
You could cache the `target` as a custom attribute on the `toggle` element.

``` javascript
Object.defineProperty( 
  toggle, 
  'a11y-toggle-' + toggle.id, 
  { 
    value: document.querySelector(
      toggle.getAttribute('aria-controls')
    ), 
    configurable: true 
  }
)
```

**Comment by KittyGiraudel** [comment]
See https://github.com/edenspiekermann/a11y-toggle/issues/7#issuecomment-196204725.
