### ISSUE TITLE
Information on browser support in README

### ISSUE THREAD

**Issue by fvsch** [edenspiekermann/a11y-toggle#28]
It would be good to have some info on supported browsers or — and maybe that is more relevant — unsupported browsers.

Given the use of `DOMContentLoaded` and `addEventListener`, I'm guessing IE8 is not supported. Has this been tried in IE9? Android browser 4.x?

**Comment by KittyGiraudel** [comment]
Indeed, I’ll add some info.

**Comment by KittyGiraudel** [comment]
Tested Android 4.1, Android 4.4 and Internet Explorer 9: works fine.

**Comment by KittyGiraudel** [comment]
Added info to README.md. Closing. :)

**Comment by fvsch** [comment]
Thanks for the tests and the doc update. :)
