### ISSUE TITLE
[aria-hidden=true] { display: none; } in example should come with disclaimer 

### ISSUE THREAD

**Issue by mikedevelops** [edenspiekermann/a11y-toggle#30]
RE: twitter conversation!

Users should consider scoping this rule to only target desired toggle elements. With this set globally there could be issues with 3rd party apps running on the page. Only identified Google Maps as being a culprit so far.

The bug in question is that Google map tiles use aria-hidden on elements within the map tree, with this rule in place Google map tiles will appear grey and map-less.

**Comment by KittyGiraudel** [comment]
Super nice catch! Thank you so much. Issued a fix (https://github.com/edenspiekermann/a11y-toggle/commit/74d9d7ff3fe98dd78f8ae96f08595691ea52c329) and a note (https://github.com/edenspiekermann/a11y-toggle/commit/6e2e85a283bd461d2c4261a42b612b090c3b5292).

**Comment by HugoGiraudel** [comment]
Issued a fix: https://github.com/edenspiekermann/a11y-toggle/commit/97b47071fbbe384090ca092c0ea1891d9608ed04.
