### ISSUE TITLE
aria-labelledby

### ISSUE THREAD

**Issue by ffoodd** [edenspiekermann/a11y-toggle#4]
Ensuring your hidden/shown region has a correct label is important, moreover if the region is expanded by default.

You may add two things:
- an `[id]` to your button;
- an `[aria-labelledby]`to your expanding region, referring to button's `[id]`.

Pretty easy to automate, I guess. Please also consider that "Read more" is generally not a good way to label anything ;)

Here are a few examples using it:
- @nico3333fr [hide/show jQuery plugin](http://a11y.nicolas-hoffmann.net/hide-show/) is the simplest, yet have been tested by some really great experts;
- [OpenAjaxAlliance example](http://www.oaa-accessibility.org/examplep/hideshow1/), more complex but older too. Please note for #3 that they also have [another related example](http://www.oaa-accessibility.org/examplep/hideshow2/), not using `[aria-owns]`at all.

What do you think about it?

**Comment by KittyGiraudel** [comment]
Sounds like a very good idea.

**Comment by KittyGiraudel** [comment]
Done in 0.2.0.
