### ISSUE TITLE
[aria-hidden="true"]

### ISSUE THREAD

**Issue by yuryzaytsev** [edenspiekermann/a11y-toggle#6]
If page has google maps, and with this atr

```
[aria-hidden="true"] {
  display: none;
}
```

the map will be hidden too.

**Comment by KittyGiraudel** [comment]
As I said in the README, “feel free to scope or restrict it”. Is this why you closed it already?

**Comment by yuryzaytsev** [comment]
I used like

```
 #content-container[aria-hidden="true"] {
  display: none;
}
```

**Comment by KittyGiraudel** [comment]
Very good. :)
