### ISSUE TITLE
Allow multiple aria-controls per target

### ISSUE THREAD

**Issue by giuseppeg** [edenspiekermann/a11y-toggle#7]
As per the current implementation multiple `toggle` buttons for the same `target` get out of sync when expanding/collapsing.
I made a testcase http://jsbin.com/koyanoxora/edit?html,css,output

In general I think that the following logic is preferable:

``` javascript
 var isExpanded = target.getAttribute('aria-hidden') === 'true';
```

In addition to that every time one clicks a `toggle` button all of the buttons with the same `namespace` value should update their `aria-expanded` value to `true|false`.

**Comment by KittyGiraudel** [comment]
Very true. I’ll see what I can do next week. :)

**Comment by KittyGiraudel** [comment]
In the case where a collapsible area would have several toggles, what should `aria-labelledby` refer to? All of them?

**Comment by KittyGiraudel** [comment]
Working prototype, but right now I need to sleep: 

``` js
(function () {

  let internalId = 0

  const $$ = (selector => Array.prototype.slice.call(document.querySelectorAll(selector)))

  const togglesMap = $$('[data-a11y-toggle]').reduce((acc, toggle) => {
    const targetId = toggle.getAttribute('data-a11y-toggle')

    toggle.id || toggle.setAttribute('id', 'a11y-toggle-' + internalId++)
    toggle.hasAttribute('aria-expanded') || toggle.setAttribute('aria-expanded', true)
    toggle.hasAttribute('aria-controls') || toggle.setAttribute('aria-controls', targetId)

    acc['#' + targetId] = acc['#' + targetId] || []
    acc['#' + targetId].push(toggle)

    return acc
  }, {})

  const targetsMap = $$(Object.keys(togglesMap)).reduce((acc, target) => {
    const labelledBy = togglesMap['#' + target.id].map(toggle => toggle.id).join(' ')

    target.hasAttribute('aria-hidden') || target.setAttribute('aria-hidden', false)
    target.hasAttribute('aria-labelledby') || target.setAttribute('aria-labelledby', labelledBy)

    acc[target.id] = target

    return acc
  }, {})

  document.addEventListener('click', event => {
    const toggle = event.target
    const target = targetsMap[toggle.getAttribute('aria-controls')]

    if (!target) return false

    const isExpanded = target.getAttribute('aria-hidden') === 'false'
    const toggles = togglesMap['#' + target.id]

    target.setAttribute('aria-hidden', isExpanded)
    toggles.forEach(toggle => toggle.setAttribute('aria-expanded', !isExpanded))
  })

}())
```

**Comment by giuseppeg** [comment]
Cool, thanks for taking a stab at this.

<blockquote>In the case where a collapsible area would have several toggles, what should aria-labelledby refer to? All of them?</blockquote>

If that is fine accessibility-wise yes, otherwise the only option is to grab the `label` text and replace `aria-labelled-by` with `aria-label` e.g.

``` javascript
target.setAttribute('aria-label', aToggle.textContent) && target.removeAttribute('aria-labelledby');
```

~~The prototype solution suffers from the perf thing from #2.~~ (edit: this is not true, I read your code at 7am :D)

Also if you want to use event delegation you'd have to do something similar to [what I showed you the other day](https://github.com/giuseppeg/a11y-toggle/blob/event-delegation/a11y-toggle.js#L29). I mean your solution is nice but it won't work in this case:

``` html
<button ... ><span>expand</span></button>
```

Here `event.target` is the `span` when it covers the `button`.

**Comment by KittyGiraudel** [comment]
> ~~The prototype solution suffers from the perf thing from #2.~~

Even if that was the case, I’d argue this is not an actual problem. Not that I think optimising for garbage collection is garbage (see what I did there?). It’s just that the likeliness to have many toggles on the same page and to remove the targets is quite low for this script.

> Also if you want to use event delegation you'd have to do something similar to what I showed you the other day. I mean your solution is nice but it won't work in this case:

Very true. I’ll probably add this in another PR though.

**Comment by KittyGiraudel** [comment]
PR pending in #12.

**Comment by KittyGiraudel** [comment]
> Also if you want to use event delegation you'd have to do something similar to what I showed you the other day. I mean your solution is nice but it won't work in this case:

Fixed in https://github.com/edenspiekermann/a11y-toggle/releases/tag/1.0.2.

**Comment by KittyGiraudel** [comment]
Done: https://github.com/edenspiekermann/a11y-toggle/releases/tag/1.0.5.
