### ISSUE TITLE
Add support for state transitions

### ISSUE THREAD

**Issue by anselmh** [edenspiekermann/a11y-toggle#8]
So, from my experience, the biggest issue of not using a clean way to build a toggle for most developers is that they need a `slideUp`/`slideDown` transition for it, not a `display: none`. 
As this is hard to achieve, they fall back towards using jQuery’s `slideToggle()` function and then, to a small part understandably, forget about proper markup afterwards.

I’m not sure if that’s the goal or the scope of the project but having it built in (either into the plugin itself or a demo) would be a benefit and maybe the key feature for people to use it.

My initial thought would be to calculate height via JS and set it on the container and then initialize a `max-height` `[x]` to `0` CSS transition. What do you think?

**Comment by KittyGiraudel** [comment]
Hey Anselm, thanks for the suggestion! I’ll investigate next week. :)

**Comment by ffoodd** [comment]
If you do so, do not forget that the collapsible region should be hidden for everyone when it's not expanded. So you can use Javascript to add a `display: none;` when `max-height` has ended transitioning, or (I suggest this one) add `visibility: hidden`, which can transition, with a `transition-delay` that equals to the `max-height`'s `transition-duration`.

Note: [this is described here](http://a11y.nicolas-hoffmann.net/hide-show/#expand_9), you may find a better way to do this :)

**Comment by KittyGiraudel** [comment]
Documentation added in demo page. :)
